# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='area',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='grupo',
            name='centro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='grupo',
            name='curso',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='site',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='professor',
            name='area',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='professor',
            name='lattes',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='professor',
            name='subarea',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='requisitos',
            field=models.TextField(default='Sem requisitos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='projeto',
            name='vagas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
